watch:
  - from: 广州 # 出发地
    to: 潮汕 # 目的地
    date:
      - "20260214" # 查询日期
      - "20260213"
    trains_filter:
      from: # 出发地筛选
        - "广州"
        - "广州东"
        - "广州新塘"
        - "广州南"
      to: # 目的地筛选
        - 普宁
        - 潮阳
        - 潮汕
        - 汕头
      beginHour: 10 # 出发时间筛选，注意是区间(9~21点)
      endHour: 21 # 到达时间筛选，注意是区间(9~21点)
    seatCategory: # 座位类型筛选
      - 二等座 # 二等座
      - 软卧 # 软卧
      - 一等座 # 一等座
    exclude: # 排除的相关
      trains:
        - "G1"       # 排除 G1 次列车
      to:
        - "上海虹桥"     # 排除终点站为上海虹桥的列车
    remark: '<at email="xx"></at>' # @人

  - from: 广州 # 出发地
    to: 潮汕 # 目的地
    date:
      - "20260214" # 查询日期
      - "20260213"
      # - "20260212"
    trains_filter:
      from: # 出发地筛选
        - "广州"
        - "广州东"
      to: # 目的地筛选
        - 潮汕
        - 汕头
      beginHour: 10 # 出发时间筛选，注意是区间(9~21点)
      endHour: 21 # 到达时间筛选，注意是区间(9~21点)
    seatCategory: # 座位类型筛选
      - 二等座 # 二等座
      - 软卧
    # exclude: # 排除的相关
    #   trains:
    #     - "G1"       # 排除 G1 次列车
    #   to:
    #     - "上海虹桥"     # 排除终点站为上海虹桥的列车
    remark: '<at email="xx"></at>' # @人

notifications:
  - # 飞书推送
    type: "Lark"
    webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxx" # 飞书机器人 Webhook URL
  #   # secret: "xxxxxxxxxx" # 签名密钥（可选，启用签名校验时填写）
# interval: 15
delay: 5
